export const quotes = [
  "A cat a day keeps the doctor away",
  "No one is perfect - that’s why pencils have erasers.",
  "You’re braver than you believe, and stronger than you seem, and smarter than you think.",
  "Oh, sweetie",
  "You look like you need a hug",
  "You are stronger than you think",
  "You have a beautiful heart",
  "Everything will be alright",
  "Treat yourself, you deserve it",
  "Take deep breaths, everything will be alright",
  "I believe in you",
  "Everything will be okay, I promise",
  "I am so proud of you",
  "Hey, you got this !",
  "Your friends love you",
  "Hugs and kisses to you",
  "You are so brave and beautiful",
  "I feel you",
  "Slow down for a minute and breathe, it’s all that matters",
  "I know you will get through this",
  "You are worth loving",
  "You are enough",
  "You are wonderful",
  "The world is a better place because you live in it",
  "Trust me : there is nothing wrong with you",
  "You are not alone",
  "I’m with you",
  "It’s okay to not be okay",
  "Are you okay ?",
  "Take your time",
  "I’m always here if you need to talk",
  "Your fears are not silly",
  "Let’s sort through this together",
  "I love you no matter what",
  "This feeling will pass",
  "I’ll just seat here with you",
  "I care about you",
  "You are important to me",
  "Tell me everything",
  "Storms don’t last forever",
  "Hold on",
  "I’ve got your back",
];

export const images = [
  "cats (1).jpeg",
  "cats (2).jpeg",
  "cats (3).jpeg",
  "cats (4).jpeg",
  "cats (5).jpeg",
  "cats (6).jpeg",
  "cats (7).jpeg",
  "cats (8).jpeg",
  "cats (9).jpeg",
  "cats (10).jpeg",
  "cats (11).jpeg",
  "cats (12).jpeg",
  "cats (13).jpeg",
  "cats (14).jpeg",
  "cats (15).jpeg",
  "cats (16).jpeg",
  "cats (17).jpeg",
  "cats (18).jpeg",
  "cats (19).jpeg",
  "cats (20).jpeg",
  "cats (21).jpeg",
  "cats (22).jpeg",
  "cats (23).jpeg",
  "cats (24).jpeg",
  "cats (25).jpeg",
];
