export const quotes = [
    'A cat a day keeps the doctor away',
    'Be so happy that, when other people look at you, they become happy too.',
    'Let your unique awesomeness and positive energy inspire confidence in others.',
    'The struggle you’re in today is developing the strength you need tomorrow.',
    'No one is perfect - that’s why pencils have erasers.',
    'Wherever you go, no matter what the weather, always bring your own sunshine.',
    'Live life to the fullest and focus on the positive.',
    'Happiness is the only thing that multiplies when you share it.',
    'Once you replace negative thoughts with positive ones, you’ll start having positive results.',
    'Winning doesn’t always mean being first. Winning means you’re doing better than you’ve done before.',
    'When we are open to new possibilities, we find them. Be open and skeptical of everything.',
    'You’re braver than you believe, and stronger than you seem, and smarter than you think.',
    'Start each day with positive thought and a graceful heart',
    'In order to carry a positive action, we must develop here a positive vision',
    'Attitude is a little thing that makes a big difference.'
]

export const images = [
    'cats (1).jpeg',
    'cats (2).jpeg',
    'cats (3).jpeg',
    'cats (4).jpeg',
    'cats (5).jpeg',
    'cats (6).jpeg',
    'cats (7).jpeg',
    'cats (8).jpeg',
    'cats (9).jpeg',
    'cats (10).jpeg',
    'cats (11).jpeg',
    'cats (12).jpeg',
    'cats (13).jpeg',
    'cats (14).jpeg',
    'cats (15).jpeg',
    'cats (16).jpeg',
    'cats (17).jpeg',
    'cats (18).jpeg',
]